export {default as Role} from "./Role"
export {default as Register} from "./Register"
export {default as Login} from "./Login"
export {default as ResetPassword} from "./ResetPassword"
export {default as NewPassword} from "./NewPassword"
export {default as Location} from "./Location"